export const COUNTRY_TRANSLATIONS = {
  Brazil: "ブラジル",
  Burundi: "ブルンジ",
  China: "中国",
  Colombia: "コロンビア",
  "Costa Rica": "コスタリカ",
  "Cote d?Ivoire": "コートジボワール",
  "Cote d'Ivoire": "コートジボワール",
  Ecuador: "エクアドル",
  "El Salvador": "エルサルバドル",
  Ethiopia: "エチオピア",
  Guatemala: "グアテマラ",
  Haiti: "ハイチ",
  Honduras: "ホンジュラス",
  India: "インド",
  Indonesia: "インドネシア",
  Japan: "日本",
  Kenya: "ケニア",
  Laos: "ラオス",
  Malawi: "マラウイ",
  Mauritius: "モーリシャス",
  Mexico: "メキシコ",
  Myanmar: "ミャンマー",
  Nicaragua: "ニカラグア",
  Panama: "パナマ",
  "Papua New Guinea": "パプアニューギニア",
  Peru: "ペルー",
  Philippines: "フィリピン",
  Rwanda: "ルワンダ",
  Taiwan: "台湾",
  "Tanzania, United Republic Of": "タンザニア",
  Tanzania: "タンザニア",
  Thailand: "タイ",
  Uganda: "ウガンダ",
  "United States": "アメリカ",
  "United States of America": "アメリカ",
  "United States (Hawaii)": "ハワイ (アメリカ)",
  Hawaii: "ハワイ (アメリカ)",
  "United States (Puerto Rico)": "プエルトリコ (アメリカ)",
  "Puerto Rico": "プエルトリコ",
  Vietnam: "ベトナム",
  Zambia: "ザンビア",
};

export function translateCountry(name) {
  if (!name) return "";
  return COUNTRY_TRANSLATIONS[name] || name;
}
