const FLAVOR_NAMES_JA = {
  "All flavors": "すべての味",
  Almond: "アーモンド",
  Apple: "リンゴ",
  Bergamot: "ベルガモット",
  Berry: "ベリー",
  "Black Tea": "紅茶",
  Blackberry: "ブラックベリー",
  Blueberry: "ブルーベリー",
  "Brown Sugar": "ブラウンシュガー",
  Caramel: "キャラメル",
  Cereal: "穀物",
  Cherry: "チェリー",
  Chocolate: "チョコレート",
  Cinnamon: "シナモン",
  "Citrus Fruit": "柑橘類",
  Clove: "クローブ",
  Cocoa: "ココア",
  "Cocoa Nibs": "カカオニブ",
  "Dark Chocolate": "ダークチョコレート",
  "Dried Fruit": "ドライフルーツ",
  "Earl Grey": "アールグレイ",
  Floral: "花のような",
  Fruity: "フルーティー",
  "Graham Cracker": "グラハムクラッカー",
  Grape: "ブドウ",
  Grapefruit: "グレープフルーツ",
  Hazelnut: "ヘーゼルナッツ",
  Hibiscus: "ハイビスカス",
  Honey: "ハチミツ",
  Jasmine: "ジャスミン",
  Lemon: "レモン",
  Lime: "ライム",
  Malt: "モルト",
  Mango: "マンゴー",
  "Maple Syrup": "メープルシロップ",
  "Milk Chocolate": "ミルクチョコレート",
  Molasses: "糖蜜",
  Nutty: "ナッツ",
  "Nutty/Cocoa": "ナッツ／ココア",
  Orange: "オレンジ",
  "Orange Blossom": "オレンジブロッサム",
  "Other Fruit": "その他の果実",
  "Passion Fruit": "パッションフルーツ",
  Peach: "桃",
  Peanut: "ピーナッツ",
  Pear: "洋梨",
  Pecan: "ピーカンナッツ",
  Pineapple: "パイナップル",
  Prune: "プルーン",
  Raisin: "レーズン",
  Raspberry: "ラズベリー",
  Roasted: "ロースト",
  Rose: "バラ",
  Spices: "スパイス",
  Strawberry: "イチゴ",
  Sweet: "甘味",
  Tangerine: "タンジェリン",
  "Tropical Fruit": "トロピカルフルーツ",
  Vanilla: "バニラ",
};

export function translateFlavor(name) {
  return FLAVOR_NAMES_JA[name] ?? name;
}

export function translateFlavorPath(parts) {
  return parts.map(translateFlavor).join(" › ");
}
